- Pandemonica, The Tired Demon -$L'alternant, il y a plus de cafe.$./assets/textures/Pandemonica/pandemonica_evil.png
- Lucy: The CEO of the Hell -$Et alors ?$./assets/textures/Lucy/lucy_constern.png
- Pandemonica, The Tired Demon -$Bouge-toi !$./assets/textures/Pandemonica/pandemonica_evil.png
- Alternant -$... $./assets/textures/Taker/Taker.png