#ifndef DEF_CONSTANTES
#define DEF_CONSTANTES

#define TAILLE_BLOC         34
#define NB_BLOCS_LARGEUR    12
#define NB_BLOCS_HAUTEUR    12
#define LARGEUR_LABEL_LVL	50
#define LARGEUR_LABEL_MENU	200
#define LARGEUR_FENETRE_JEU     TAILLE_BLOC * NB_BLOCS_LARGEUR
#define HAUTEUR_FENETRE_JEU     TAILLE_BLOC * NB_BLOCS_HAUTEUR
#define LARGEUR_FENETRE			LARGEUR_FENETRE_JEU + 100
#define HAUTEUR_FENETRE			HAUTEUR_FENETRE_JEU + 100

enum {STATIC, HAUT, BAS, GAUCHE, DROITE};
enum {VIDE, MUR, CAISSE, OBJECTIF, CAISSE_OK, MARIO};

#endif