#ifndef DEF_CONSTANTES
#define DEF_CONSTANTES

#define LARGEUR_FENETRE		1366
#define HAUTEUR_FENETRE		768

#define TAILLE_BLOC         34
#define NB_BLOCS_LARGEUR    12
#define NB_BLOCS_HAUTEUR    12
#define LARGEUR_LABEL_LVL	50
#define LARGEUR_LABEL_MENU	200
#define SIZE_SPEECH			HAUTEUR_FENETRE * 4 / 6

#define LARGEUR_FENETRE_JEU     TAILLE_BLOC * NB_BLOCS_LARGEUR
#define HAUTEUR_FENETRE_JEU     TAILLE_BLOC * NB_BLOCS_HAUTEUR

#define ERROR_EXIT	0
#define ERROR_NEXT	1

enum {STATIC, HAUT, BAS, GAUCHE, DROITE};
enum {VIDE, MUR, CAISSE, OBJECTIF, CAISSE_OK, MARIO};

#endif